# Generated by Django 4.2.26 on 2026-01-03 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_alter_userfollow_followed'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='userfollow',
            constraint=models.CheckConstraint(check=models.Q(('follower', models.F('followed')), _negated=True), name='prevent_self_follow'),
        ),
    ]
