# Generated by Django 4.2.26 on 2026-01-16 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_rename_username_post_user_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-timestamp']},
        ),
    ]
