# Generated by Django 4.2.26 on 2026-01-16 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_alter_post_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user_id',
            new_name='user',
        ),
    ]
