# Generated by Django 4.2.26 on 2026-01-23 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_rename_user_id_post_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='count',
        ),
        migrations.AddField(
            model_name='likes',
            name='is_active',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='likes',
            index=models.Index(fields=['post', 'is_active'], name='post_is_active_idx'),
        ),
        migrations.AddIndex(
            model_name='likes',
            index=models.Index(fields=['post', 'user', 'is_active'], name='post_user_is_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='likes',
            constraint=models.UniqueConstraint(fields=('user', 'post'), name='unique_user_like_post'),
        ),
    ]
