# Generated by Django 4.2.26 on 2026-01-23 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_remove_likes_count_likes_is_active_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='likes',
            new_name='post_user_is_idx',
            old_name='post_user_is_active_idx',
        ),
    ]
