# Generated by Django 4.2.26 on 2026-01-23 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_rename_post_user_is_active_idx_post_user_is_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='likes',
            name='post_user_is_idx',
        ),
        migrations.AddIndex(
            model_name='likes',
            index=models.Index(fields=['post', 'user'], name='post_user_is_idx'),
        ),
    ]
