# Generated by Django 4.2.26 on 2026-01-26 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_remove_likes_post_user_is_idx_likes_post_user_is_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='network.post'),
        ),
    ]
